"""Federal Register DocumentField values from the checked-in OpenAPI snapshot."""

DOCUMENT_FIELDS = (
    "abstract",
    "action",
    "agencies",
    "agency_names",
    "amendatory_instructions",
    "body_html_url",
    "cfr_references",
    "cfr_topics",
    "citation",
    "comment_url",
    "comments_close_on",
    "correction_of",
    "corrections",
    "dates",
    "disposition_notes",
    "docket_id",
    "docket_ids",
    "dockets",
    "document_number",
    "effective_on",
    "end_page",
    "excerpts",
    "executive_order_notes",
    "executive_order_number",
    "explanation",
    "full_text_xml_url",
    "html_url",
    "images",
    "images_metadata",
    "json_url",
    "mods_url",
    "not_received_for_publication",
    "page_length",
    "page_views",
    "pdf_url",
    "president",
    "presidential_document_number",
    "proclamation_number",
    "public_inspection_pdf_url",
    "publication_date",
    "raw_text_url",
    "regulation_id_number_info",
    "regulation_id_numbers",
    "regulations_dot_gov_info",
    "regulations_dot_gov_url",
    "related_documents",
    "significant",
    "signing_date",
    "start_page",
    "subtype",
    "title",
    "toc_doc",
    "toc_subject",
    "topics",
    "type",
    "volume",
)

JSONB_FIELDS = frozenset(
    {
        "agencies",
        "agency_names",
        "amendatory_instructions",
        "cfr_references",
        "cfr_topics",
        "correction_of",
        "corrections",
        "docket_ids",
        "dockets",
        "images",
        "images_metadata",
        "page_views",
        "president",
        "regulation_id_number_info",
        "regulation_id_numbers",
        "regulations_dot_gov_info",
        "related_documents",
        "topics",
    }
)

REQUIRED_FIELDS = frozenset(
    {"document_number", "title", "type", "publication_date", "html_url"}
)
