apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - name: Trace ID
          matcherType: label
          matcherRegex: '^tid$'
          datasourceUid: tempo
          url: '$${__value.raw}'
          urlDisplayLabel: Open trace
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: -2s
        spanEndTimeShift: 2s
        tags:
          - key: service.name
            value: service_name
        filterByTraceID: true
        filterBySpanID: false
        customQuery: true
        query: '{service_name="maiven-web"} | tid=`$${__trace.traceId}`'
