ALTER TABLE "documents" ADD COLUMN "type" text DEFAULT 'RULE' NOT NULL;--> statement-breakpoint
ALTER TABLE "documents" ALTER COLUMN "type" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "action" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "agency_names" jsonb;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "amendatory_instructions" jsonb;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "body_html_url" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "cfr_references" jsonb;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "cfr_topics" jsonb;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "citation" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "comment_url" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "comments_close_on" date;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "correction_of" jsonb;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "corrections" jsonb;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "dates" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "disposition_notes" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "docket_id" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "docket_ids" jsonb;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "dockets" jsonb;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "end_page" integer;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "excerpts" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "executive_order_notes" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "executive_order_number" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "explanation" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "full_text_xml_url" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "images" jsonb;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "images_metadata" jsonb;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "json_url" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "mods_url" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "not_received_for_publication" boolean;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "page_length" integer;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "page_views" jsonb;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "pdf_url" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "president" jsonb;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "presidential_document_number" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "proclamation_number" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "public_inspection_pdf_url" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "raw_text_url" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "regulation_id_number_info" jsonb;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "regulation_id_numbers" jsonb;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "regulations_dot_gov_info" jsonb;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "regulations_dot_gov_url" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "related_documents" jsonb;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "significant" boolean;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "signing_date" date;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "start_page" integer;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "subtype" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "toc_doc" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "toc_subject" text;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "topics" jsonb;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "volume" integer;
